// packages/vue-taro/src/index.tsx
import {App, createApp as createCSRApp, defineComponent, onBeforeUnmount, ref} from 'vue';

import {AppConfig, UNListener} from '@elux/app';
import {buildProvider, coreConfig, IStore, locationToUrl, setCoreConfig} from '@elux/core';
import {createRouter} from '@elux/route-mp';
import {onShow, taroHistory} from '@elux/taro';
import {EWindow} from '@elux/vue-components';
import {useDidHide, useDidShow} from '@tarojs/taro';

export {connectStore, DocumentHead, Else, Link, Switch} from '@elux/vue-components';
export type {DocumentHeadProps, ElseProps, LinkProps, SwitchProps} from '@elux/vue-components';

export * from '@elux/app';

setCoreConfig({
  Platform: 'taro',
});

/**
 * 小程序Page页面
 *
 * @public
 */
export const EluxPage: Elux.Component = defineComponent({
  setup() {
    const router = coreConfig.UseRouter!();
    const store = ref<IStore>();
    let unlink: UNListener | undefined;
    useDidShow(() => {
      if (!unlink) {
        unlink = router.addListener(({newStore}) => {
          store.value = newStore;
        });
      }
      onShow();
    });
    useDidHide(() => {
      if (unlink) {
        unlink();
        unlink = undefined;
      }
    });
    onBeforeUnmount(() => {
      if (unlink) {
        unlink();
        unlink = undefined;
      }
    });
    return () => (store.value ? <EWindow store={store.value} key={store.value.sid} /> : <div className="g-page-loading">Loading...</div>);
  },
}) as any;

let cientSingleton: App;

/**
 * 创建应用
 *
 * @remarks
 * 应用唯一的创建入口
 *
 * @param appConfig - 应用配置
 * @param appOptions - 应用生命周期钩子
 *
 * @returns
 * 返回Vue实例
 *
 * @example
 * ```js
 * createApp(config, {
 *  onLaunch(){
 *  }
 * })
 * ```
 *
 * @public
 */
export function createApp(appConfig: AppConfig, appOptions: Record<string, any> = {}): App {
  if (!cientSingleton) {
    const onLaunch = appOptions.onLaunch;
    appOptions.onLaunch = function (options: any) {
      const location = taroHistory.getLocation();
      router.init({url: locationToUrl(location)}, {});
      onLaunch && onLaunch(options);
    };
    cientSingleton = createCSRApp(appOptions);
    const router = createRouter(taroHistory);
    buildProvider(cientSingleton, router);
  }
  return cientSingleton;
}

// packages/react-taro/src/index.tsx
import {useEffect, useRef, useState} from 'react';

import {AppConfig} from '@elux/app';
import {buildProvider, coreConfig, getClientRouter, IStore, locationToUrl, setCoreConfig, UNListener} from '@elux/core';
import {EWindow} from '@elux/react-components';
import {createRouter} from '@elux/route-mp';
import {onShow, taroHistory} from '@elux/taro';
import {useDidHide, useDidShow} from '@tarojs/taro';

export {DocumentHead, Else, Link, Switch} from '@elux/react-components';
export type {DocumentHeadProps, ElseProps, LinkProps, SwitchProps} from '@elux/react-components';

export {connectRedux, connectStore, createSelectorHook, shallowEqual, useSelector} from '@elux/react-redux';
export type {GetProps, InferableComponentEnhancerWithProps} from '@elux/react-redux';

export * from '@elux/app';

setCoreConfig({
  Platform: 'taro',
});

/**
 * 小程序Page页面
 *
 * @public
 */
export const EluxPage: Elux.Component = () => {
  const router = coreConfig.UseRouter!();
  const [store, setStore] = useState<IStore>();
  const unlink = useRef<UNListener>();
  useDidShow(() => {
    if (!unlink.current) {
      unlink.current = router.addListener(({newStore}) => {
        setStore(newStore);
      });
    }
    onShow();
  });
  useDidHide(() => {
    if (unlink.current) {
      unlink.current();
      unlink.current = undefined;
    }
  });
  useEffect(() => {
    return () => {
      if (unlink.current) {
        unlink.current!();
        unlink.current = undefined;
      }
    };
  }, []);

  return store ? <EWindow store={store} key={store.sid} /> : <div className="g-page-loading">Loading...</div>;
};

let cientSingleton: Elux.Component<{children: any}>;

/**
 * 创建应用
 *
 * @param appConfig - 应用配置
 *
 * @returns
 * 返回包含Provider组件
 *
 * @example
 * ```js
 * render () {
 *   const Provider = createApp(appConfig);
 *   return <Provider>{this.props.children}</Provider>
 * }
 * ```
 *
 * @public
 */
export function createApp(appConfig: AppConfig): Elux.Component<{children: any}> {
  if (!cientSingleton) {
    const router = createRouter(taroHistory);
    cientSingleton = buildProvider({}, router);
  }
  const location = taroHistory.getLocation();
  if (location.pathname) {
    const router = getClientRouter();
    router.init({url: locationToUrl(location)}, {});
  }
  return cientSingleton;
}
