// packages/vue-taro/src/index.tsx
import {App, createApp as createCSRApp, defineComponent, onBeforeUnmount, ref} from 'vue';

import {AppConfig, UNListener} from '@elux/app';
import {buildProvider, coreConfig, IStore, setCoreConfig} from '@elux/core';
import type {Router} from '@elux/route';
import {createRouter} from '@elux/route-mp';
import {onShow, taroHistory} from '@elux/taro';
import {EWindow} from '@elux/vue-components';
import {useDidHide, useDidShow} from '@tarojs/taro';

export {DocumentHead, Else, Link, Switch} from '@elux/vue-components';
export type {DocumentHeadProps, ElseProps, LinkProps, SwitchProps} from '@elux/vue-components';

export * from '@elux/app';

setCoreConfig({
  Platform: 'taro',
});

/**
 * 小程序Page入口
 *
 * @public
 */
export const EluxPage: Elux.Component = defineComponent({
  setup() {
    const router = coreConfig.UseRouter!() as Router;
    const store = ref<IStore>();
    let unlink: UNListener | undefined;
    useDidShow(() => {
      if (!unlink) {
        unlink = router.addListener(({newStore}) => {
          store.value = newStore;
        });
      }
      onShow();
    });
    useDidHide(() => {
      if (unlink) {
        unlink();
        unlink = undefined;
      }
    });
    onBeforeUnmount(() => {
      if (unlink) {
        unlink();
        unlink = undefined;
      }
    });
    return () => (store.value ? <EWindow store={store.value} key={store.value.sid} /> : <div className="g-page-loading">Loading...</div>);
  },
}) as any;

let cientSingleton: App;

/**
 * 创建应用
 *
 * @remarks
 * 应用唯一的创建入口
 *
 * @param appConfig - 应用配置
 * @param appOptions - 应用生命周期钩子
 *
 * @returns
 * 返回Vue实例
 *
 * @example
 * ```js
 * createApp(config, {
 *  onLaunch(){
 *  }
 * })
 * ```
 *
 * @public
 */
export function createApp(appConfig: AppConfig, appOptions: Record<string, any> = {}): App {
  if (!cientSingleton) {
    const onLaunch = appOptions.onLaunch;
    appOptions.onLaunch = function (options: any) {
      const router = createRouter(taroHistory);
      buildProvider(cientSingleton, router);
      onLaunch && onLaunch(options);
    };
    cientSingleton = createCSRApp(appOptions);
  }
  return cientSingleton;
}

// packages/react-taro/src/index.ts
import {useEffect, useRef, useState} from 'react';

import {AppConfig} from '@elux/app';
import {buildProvider, coreConfig, getAppProvider, IStore, UNListener} from '@elux/core';
import {createRouter} from '@elux/route-mp';
import {taroHistory, onShow} from '@elux/taro';
import {useDidHide, useDidShow} from '@tarojs/taro';
import type {Router} from '@elux/route';

export {DocumentHead, Else, EWindow, Link, Switch} from '@elux/react-components';
export type {DocumentHeadProps, ElseProps, LinkProps, SwitchProps} from '@elux/react-components';

export {connectRedux, createSelectorHook, shallowEqual, useSelector} from '@elux/react-redux';
export type {GetProps, InferableComponentEnhancerWithProps} from '@elux/react-redux';

export * from '@elux/app';

/**
 * 在小程序Page中获取Store
 *
 * @public
 */
export function useCurrentStore(): IStore | undefined {
  const router = coreConfig.UseRouter!() as Router;
  const [store, setStore] = useState<IStore>();
  const unlink = useRef<UNListener>();
  useDidShow(() => {
    if (!unlink.current) {
      unlink.current = router.addListener(({newStore}) => {
        setStore(newStore);
      });
    }
    onShow();
  });
  useDidHide(() => {
    if (unlink.current) {
      unlink.current!();
      unlink.current = undefined;
    }
  });
  useEffect(() => {
    return () => {
      if (unlink.current) {
        unlink.current!();
        unlink.current = undefined;
      }
    };
  }, []);

  return store;
}

/**
 * @public
 */
export type EluxApp = {
  render(): Elux.Component<{children: any}>;
};

let cientSingleton: EluxApp = undefined as any;

/**
 * 创建应用(CSR)
 *
 * @param appConfig - 应用配置
 *
 * @returns
 * 返回包含`render`方法的实例
 *
 * @example
 * ```js
 * render () {
 *   const Provider = createApp(appConfig).render();
 *   return <Provider>{this.props.children}</Provider>
 * }
 * ```
 *
 * @public
 */
export function createApp(appConfig: AppConfig): EluxApp {
  if (cientSingleton) {
    return cientSingleton;
  }
  const router = createRouter(taroHistory);
  cientSingleton = {
    render() {
      return getAppProvider();
    },
  };
  return buildProvider({}, router);
}
