// packages/react-web/src/components/Switch.tsx
import React, {ReactNode} from 'react';

interface Props {
  elseView?: ReactNode;
  children: ReactNode;
}
const Component: React.FC<Props> = ({children, elseView}) => {
  const arr: ReactNode[] = [];
  React.Children.forEach(children, (item) => {
    item && arr.push(item);
  });
  if (arr.length > 0) {
    return <>{arr[0]}</>;
  }
  return <>{elseView}</>;
};

export default React.memo(Component);

// packages/vue-components/src/Switch.tsx
import {Fragment, h, VNode, Comment} from 'vue';

interface Props {
  elseView?: VNode;
}
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export default function (props: Props, context: {slots: {default?: () => VNode[]; elseView?: () => VNode[]}}) {
  const arr: VNode[] = [];
  const children: VNode[] = context.slots.default ? context.slots.default() : [];
  children.forEach((item) => {
    if (item.type !== Comment) {
      arr.push(item);
    }
  });
  if (arr.length > 0) {
    return h(Fragment, null, [arr[0]]);
  }

  return h(Fragment, null, props.elseView ? [props.elseView] : context.slots.elseView ? context.slots.elseView() : []);
}

// export default defineComponent({
//   props: {
//     elseView: {
//       type: Object as PropType<VNode>,
//     },
//   },
//   setup(props, {slots}) {
//     return () => {
//       const arr: VNode[] = [];
//
//       children.forEach((item) => {
//         if (item.type !== Comment) {
//           arr.push(item);
//         }
//       });
//       if (arr.length > 0) {
//         return <>{arr[0]}</>;
//       }
//       return <>{props.elseView}</>;
//     };
//   },
// });
