// packages/vue-components/src/base.tsx
import {Component} from 'vue';
import {env, IStore, buildConfigSetter} from '@elux/core';
import {IBaseRouter} from '@elux/route';

export const vueComponentsConfig: {
  setPageTitle(title: string): void;
  Provider: Component<{store: IStore}>;
  LoadComponentOnError: Component<{message: string}>;
  LoadComponentOnLoading: Component<{}>;
} = {
  setPageTitle(title: string) {
    return (env.document.title = title);
  },
  Provider: null as any,
  LoadComponentOnError: ({message}: {message: string}) => <div class="g-component-error">{message}</div>,
  LoadComponentOnLoading: () => <div class="g-component-loading">loading...</div>,
};

export const setVueComponentsConfig = buildConfigSetter(vueComponentsConfig);
export interface EluxContext {
  deps?: Record<string, boolean>;
  documentHead: string;
  store?: IStore;
  router?: IBaseRouter<any, string>;
}
export const EluxContextKey = '__EluxContext__';

// packages/react-components/src/base.tsx
import React, {ComponentType} from 'react';
import {env, IStore, buildConfigSetter} from '@elux/core';
import {IBaseRouter} from '@elux/route';

export const reactComponentsConfig: {
  setPageTitle(title: string): void;
  Provider: ComponentType<{store: IStore}>;
  LoadComponentOnError: ComponentType<{message: string}>;
  LoadComponentOnLoading: ComponentType<{}>;
} = {
  setPageTitle(title: string) {
    return (env.document.title = title);
  },
  LoadComponentOnError: ({message}: {message: string}) => <div className="g-component-error">{message}</div>,
  LoadComponentOnLoading: () => <div className="g-component-loading">loading...</div>,
} as any;

export const setReactComponentsConfig = buildConfigSetter(reactComponentsConfig);
export interface EluxContext {
  deps?: Record<string, boolean>;
  documentHead: string;
  store?: IStore;
  router?: IBaseRouter<any, string>;
}
export const EluxContextComponent = React.createContext<EluxContext>({documentHead: ''});
